name: deploy-to-vps

on:
  push:
    branches:
      - master
jobs:
  Deploy-to-VPS:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_DEPLOY_DIR }}
            git pull origin master
            php artisan migrate:fresh --seed --env=testing
            php artisan test
            php artisan migrate --force
